images:
# Compiler / Runtime
# - Golang
- name: go
  description: Go (golang) is a general purpose, higher-level, imperative programming language.
  provides:
  - go
  image: docker.io/golang:1.13-buster
  cache:
  - name: golang
    directory: /go/pkg
# - Java
- name: java
  description: OpenJDK 11
  provides:
  - java
  image: docker.io/adoptopenjdk:11-jdk-hotspot
  cache:
  - name: gradle
    directory: /root/.gradle
  - name: maven
    directory: /root/.m2
# - Node
- name: npm
  description: Node.js is a JavaScript-based platform for server-side and networking applications.
  provides:
  - npm
  - yarn
  image: docker.io/node:10-alpine
  cache:
  - name: node-10
    directory: /root/.npm
# Shell
- name: bats
  description: Bash Automated Testing System
  provides:
  - bats
  image: docker.io/bats/bats:latest
# Lint
# - Shell
- name: shellcheck
  description: ShellCheck -- Shell script analysis tool
  provides:
  - shellcheck
  image: docker.io/koalaman/shellcheck:v0.7.0
  entrypoint: /bin/bash
# Optimize
# - UPX
- name: upx
  description: UPX is a free, portable, extendable, high-performance executable packer for several executable formats.
  provides:
  - upx
  image: docker.io/envcli/upx:latest
# Static Site Generators
- name: hugo
  description: The worlds fastest framework for building websites.
  provides:
  - hugo
  - htmlproofer
  image: docker.io/cibuilds/hugo:0.58.2
# Infrastructure
# - Kubernetes
- name: KubeCTL
  description: Use the Kubernetes command-line tool, kubectl, to deploy and manage applications on Kubernetes.
  provides:
  - kubectl
  image: docker.io/envcli/kubectl:1.12.3
  shell: sh
  cache:
  - name: kubectl
    directory: /root/.kube
# - Helm
- name: Helm Client
  description: Helm is a tool for managing Kubernetes charts. Charts are packages of pre-configured Kubernetes resources.
  provides:
  - helm
  image: docker.io/envcli/helm:2.14.0
  shell: sh
  directory: /data
  cache:
  - name: kubectl
    directory: /root/.kube
  - name: helm
    directory: /root/.helm
