images:
# Compiler / Runtime
# - Golang
- name: go
  description: Go (golang) is a general purpose, higher-level, imperative programming language.
  provides:
  - go
  image: docker.io/golang:1.13-buster
  cache:
  - name: golang
    directory: /go/pkg
- name: godep
  description: dep is a prototype dependency management tool for Go. It requires Go 1.8 or newer to compile.
  provides:
  - dep
  image: docker.io/envcli/go-dep:0.5.0
  directory: /go/src/project
# - Java
- name: java
  description: OpenJDK 11
  provides:
  - java
  image: docker.io/adoptopenjdk:11-jdk-hotspot
  cache:
  - name: gradle
    directory: /root/.gradle
  - name: maven
    directory: /root/.m2
# - Node
- name: npm
  description: Node.js is a JavaScript-based platform for server-side and networking applications.
  provides:
  - npm
  - yarn
  image: docker.io/node:10-alpine
  cache:
  - name: node-10
    directory: /root/.npm
# - Python
- name: python
  description: Python is a programming language that lets you work quickly and integrate systems more effectively.
  provides:
  - python
  - pip
  image: docker.io/library/python:3-alpine
  cache:
  - name: python-3.7
    directory: /usr/local/lib/python3.7/site-packages
# Shell
- name: bats
  description: Bash Automated Testing System
  provides:
  - bats
  image: docker.io/bats/bats:latest
# Lint
# - Shell
- name: shellcheck
  description: ShellCheck -- Shell script analysis tool
  provides:
  - shellcheck
  image: docker.io/koalaman/shellcheck:v0.7.0
  entrypoint: /bin/bash
# Optimize
# - UPX
- name: upx
  description: UPX is a free, portable, extendable, high-performance executable packer for several executable formats.
  provides:
  - upx
  image: docker.io/envcli/upx:latest
# Static Site Generators
- name: hugo
  description: The worlds fastest framework for building websites.
  provides:
  - hugo
  - htmlproofer
  image: docker.io/cibuilds/hugo:0.58.2
# Infrastructure
# - Kubernetes
- name: KubeCTL
  description: Use the Kubernetes command-line tool, kubectl, to deploy and manage applications on Kubernetes.
  provides:
  - kubectl
  image: docker.io/envcli/kubectl:1.12.3
  cache:
  - name: kubectl
    directory: /root/.kube
# - Helm
- name: Helm Client
  description: Helm is a tool for managing Kubernetes charts. Charts are packages of pre-configured Kubernetes resources.
  provides:
  - helm
  image: docker.io/lachlanevenson/k8s-helm:v3.0.0
  directory: /data
  cache:
  - name: kubectl
    directory: /root/.kube
  - name: helm-cfg
    directory: /root/.config/helm
  - name: helm-data
    directory: /root/.local/share/helm
  - name: helm-cache
    directory: /root/.cache/helm
# - Ansible
- name: Ansible
  description: Ansible is open source software that automates software provisioning, configuration management, and application deployment. Ansible connects via SSH, remote PowerShell or via other remote APIs.
  provides:
  - ansible
  - ansible-playbook
  - ansible-pull
  image: docker.io/envcli/ansible:latest
  cache:
  - name: ssh
    directory: /root/.ssh
# Scripting
- name: normalizeci
  description: A tool to turn the continious integration / deployment variables into a common format for generally usable scripts without any dependencies.
  provides:
  - normalizeci
  image: docker.io/envcli/normalizeci:0.2.0
- name: jq
  description: jq is a lightweight and flexible command-line JSON processor
  provides:
  - jq
  image: docker.io/fluidattacks/alpine-kaniko
# Changelog
- name: git-chglog
  description: CHANGELOG generator implemented in Go (Golang).
  provides:
  - git-chglog
  image: docker.io/envcli/git-chglog:0.9.1
# Presentation
- name: RevealJS
  description: The HTML Presentation Framework
  provides:
  - asciidoctor-revealjs
  image: docker.io/envcli/revealjs:latest
