#!/usr/bin/env bash

# debug mode
DEBUG=${DEBUG:-false}
if [ "$DEBUG" == "true" ]; then
    echo "-> Debugging mode enabled ..."
    set -x
fi

# func: prepare
function act-common-prepare()
{
    # prerequisites
    # - envcli
    if ! command -v envcli > /dev/null; then
        echo "-> envcli not available. Please run the modular pipeline installation script!"
        exit 1
    fi
    # - normalizeci
    if ! command -v normalizeci > /dev/null; then
        echo "-> normalizeci not available. Please run the modular pipeline installation script!"
        exit 1
    fi
    # - docker
    if ! command -v docker > /dev/null; then
        echo "-> docker not available. Please install docker!"
        exit 1
    fi

    # normalize ci variables
    echo "-> execute: normalizeci"
    eval $(normalizeci)

    # proxy
    export HTTP_PROXY=${HTTP_PROXY:-}
    export HTTPS_PROXY=${HTTPS_PROXY:-}
    export PROXY_HOST=${PROXY_HOST:-}
    export PROXY_PORT=${PROXY_PORT:-}
    export JAVA_PROXY_OPTS="-Dhttp.proxyHost=$PROXY_HOST -Dhttp.proxyPort=$PROXY_PORT -Dhttps.proxyHost=$PROXY_HOST -Dhttps.proxyPort=$PROXY_PORT"
}

# pathing (temporary) TODO: remove
export NCI_PROJECT_DIR="$(pwd)"

# func: run hook / $1 = hook name
function act-common-hook()
{
    # repository hooks
    if test -f "$NCI_PROJECT_DIR/.ci/$1.sh"; then
        echo "-> execute: repository hook \`$1\`"
        $NCI_PROJECT_DIR/.ci/$1.sh
    fi
}
