#!/usr/bin/env bash
set -euo pipefail
ACTION_CATEGORY="optimize"
ACTION_NAME="upx"

# common
LOCAL_PATH=${BASH_SOURCE%/*}
source "$LOCAL_PATH/pipeline-common"

# main
function main()
{
  # configuration
  ARTIFACT_DIR=${ARTIFACT_DIR:-dist}
  UPX_ARGS=${UPX_ARGS:---brute}

  # execute
  echo "-> Execute: Optimization"
  for file in $ARTIFACT_DIR/*
  do
    echo "--> Compressing $file ..."
    upx $UPX_ARGS "$file"
  done
}

# entrypoint
case "${1:-}" in
  help)
    echo "Used to compress executable files using upx (the Ultimate Packer for eXecutables)"
    echo ""
    echo "Environment:"
    echo "* DEBUG: Can be set to true to enable debugging"
    echo "* ARTIFACT_DIR: All files from this directory will be published on bintray (default: dist)"
    echo "* UPX_ARGS: Default is `--brute`, use `--best --ultra-brute` for best compression."
    ;;
  *)
    _log_message "Running action [$ACTION_CATEGORY.$ACTION_NAME]" "INFO"
    _prepare
    _run_hook "pre-$ACTION_CATEGORY-$ACTION_NAME"
    main "$@"
    _run_hook "post-$ACTION_CATEGORY-$ACTION_NAME"
;;
esac
