#!/usr/bin/env bash
set -euo pipefail
ACTION_CATEGORY="java"
ACTION_NAME="test"

# common
LOCAL_PATH=${BASH_SOURCE%/*}
source "$LOCAL_PATH/action-common"
source "$LOCAL_PATH/action-java-common"

# main
function main()
{
  # detect build system
  act-java-common-detect
  echo "-> execute: test"
  if echo "$BUILD_SYSTEM" | grep -q 'gradle'; then
    # gradle
    act-java-common-gradle test
  elif echo "$BUILD_SYSTEM" | grep -q 'maven'; then
    # maven
    act-java-common-maven test
  else
    echo "--> error: unknown build system!"
    echo "Supported are: gradle, maven"
    exit 1
  fi
}

# entrypoint
case "${1:-}" in
  help)
    echo "Build script for java projects"
    echo ""
    echo "Environment:"
    echo "* DEBUG: Can be set to true to enable debugging"
    ;;
  *)
    echo "Running action [$ACTION_CATEGORY.$ACTION_NAME]"
    act-common-prepare
    act-common-hook "pre-$ACTION_CATEGORY-$ACTION_NAME"
    main "$@"
    act-common-hook "post-$ACTION_CATEGORY-$ACTION_NAME"
;;
esac
