#!/usr/bin/env bash
set -euo pipefail
ACTION_CATEGORY="go"
ACTION_NAME="test"

# common
LOCAL_PATH=${BASH_SOURCE%/*}
source "$LOCAL_PATH/pipeline-common"

# main
function main()
{
    # configuration
    VERBOSE=${VERBOSE:-false}

    # run tests
    echo "-> execute: tests"
    if echo "$VERBOSE" | grep -q 'true'; then
        envcli run go test -v ./...
    else
        envcli run go test ./...
    fi
}

# entrypoint
case "${1:-}" in
  help)
    echo "Used to run go tests"
    echo ""
    echo "Environment:"
    echo "* DEBUG: Can be set to true to enable debugging"
    echo "* VERBOSE: Will print additional test information on execution"
    ;;
  *)
    _log_message "Running action [$ACTION_CATEGORY.$ACTION_NAME]" "INFO"
    _prepare
    _run_hook "pre-$ACTION_CATEGORY-$ACTION_NAME"
    main "$@"
    _run_hook "post-$ACTION_CATEGORY-$ACTION_NAME"
;;
esac
