#!/usr/bin/env bash
set -euo pipefail
ACTION_CATEGORY="shell"
ACTION_NAME="test"

# common
LOCAL_PATH=${BASH_SOURCE%/*}
source "$LOCAL_PATH/pipeline-common"

# main
function main()
{
  # configuration
  TEST_DIR=${TEST_DIR:-tests}

  # get dependencies
  _run_in_container bats --tap --recursive $TEST_DIR
}

# entrypoint
case "${1:-}" in
  help)
    echo "Bash Automated Testing System Tests"
    echo ""
    echo "Environment:"
    echo "* DEBUG: Can be set to true to enable debugging"
    ;;
  *)
    _log_message "Running action [$ACTION_CATEGORY.$ACTION_NAME]" "INFO"
    _prepare
    _run_hook "pre-$ACTION_CATEGORY-$ACTION_NAME"
    main "$@"
    _run_hook "post-$ACTION_CATEGORY-$ACTION_NAME"
;;
esac
