#!/usr/bin/env bash
set -euo pipefail
ACTION_CATEGORY="container"
ACTION_NAME="build"

# common
LOCAL_PATH=${BASH_SOURCE%/*}
source "$LOCAL_PATH/pipeline-common"
source "$LOCAL_PATH/action-common-container"

# main
function main()
{
  # configuration
  DOCKERFILE_PATH="${DOCKERFILE_PATH:-.}"
  DOCKERFILE_NAME="${DOCKERFILE_NAME:-Dockerfile}"
  DOCKERFILE_URL_DEFAULT="${DOCKERFILE_URL_DEFAULT:-}"

  # support for DOCKERFILE_URL_DEFAULT
  if ! test -f "$DOCKERFILE_PATH/$DOCKERFILE_NAME"; then
    _log_message "no local dockerfile provided at [$DOCKERFILE_PATH/$DOCKERFILE_NAME]!" "DEBUG"

    if [ -z "$DOCKERFILE_DEFAULT" ]; then
      _log_message "no dockerfile provided at [$DOCKERFILE_PATH/$DOCKERFILE_NAME] and no DOCKERFILE_DEFAULT set!" "ERROR"
      exit 1
    else
      _log_message "using default dockerfile from [$DOCKERFILE_DEFAULT] at [$DOCKERFILE_PATH/$DOCKERFILE_NAME]" "INFO"
      curl -L -s -o "$DOCKERFILE_PATH/$DOCKERFILE_NAME" "$DOCKERFILE_DEFAULT"
      USED_DEFAULT_DOCKER=true
    fi
  fi

  # parse the dockerfile to find the base image (+split repo / tag)
  container_parse_dockerfile_baseimage "$DOCKERFILE_PATH/$DOCKERFILE_NAME"
  _log_message "container image - repository: $CONTAINER_BASE_IMAGE_REPOSITORY" "DEBUG"
  _log_message "container image - tag: $CONTAINER_BASE_IMAGE_TAG" "DEBUG"

  # build
  IFS=',' read -r -a artifactBuildArchArray <<< $(echo "$ARTIFACT_BUILD_ARCHS")
  for VALUE in "${artifactBuildArchArray[@]}"; do
    IFS='_' read -r -a row <<< "$VALUE"
    local buildOS="${row[0]}"
    local buildArch="${row[1]}"

    # run build
    container_build "$CONTAINER_REPO" "$CONTAINER_TAG" "$CONTAINER_BASE_IMAGE_REPOSITORY" "$CONTAINER_BASE_IMAGE_TAG" "$buildOS" "$buildArch"
  done

  # create manifest
  # create_container_manifest "$CONTAINER_REPO:$CONTAINER_TAG" "$ARTIFACT_BUILD_ARCHS"

  # remove default dockerfile if used
  if echo "${USED_DEFAULT_DOCKER:-false}" | grep -q 'true'; then
    _log_message "removed temporary dockerfile" "DEBUG"
    rm "$DOCKERFILE_PATH/$DOCKERFILE_NAME" >> /dev/null
  fi
}

# entrypoint
case "${1:-}" in
  help)
    echo "Used to package a app with a dockerfile"
    echo ""
    echo "Environment:"
    echo "* DEBUG: Can be set to true to enable debugging."
    echo "* DOCKERFILE_PATH: Path of the dockerfile, by default the current working directory."
    echo "* DOCKERFILE_NAME: Name of the dockerfile. (default: Dockerfile)"
    echo "* DOCKERFILE_URL_DEFAULT: A url to a default dockerfile to use, if the local dockerfile wasn't found/provided."
    ;;
  *)
    _log_message "Running action [$ACTION_CATEGORY.$ACTION_NAME]" "INFO"
    _prepare
    _run_hook "pre-$ACTION_CATEGORY-$ACTION_NAME"
    main "$@"
    _run_hook "post-$ACTION_CATEGORY-$ACTION_NAME"
;;
esac
