#!/usr/bin/env bash
set -euo pipefail
ACTION_CATEGORY="java"
ACTION_NAME="build"

# common
LOCAL_PATH=${BASH_SOURCE%/*}
source "$LOCAL_PATH/pipeline-common"
source "$LOCAL_PATH/action-common-java"

# main
function main()
{
  # configuration
  ARTIFACT_DIR=${ARTIFACT_DIR:-dist}

  # make sure the directory exists
  mkdir -p $ARTIFACT_DIR

  # detect build system
  act-java-common-detect

  # run build
  if echo "$BUILD_SYSTEM" | grep -q 'gradle'; then
    # gradle
    act-java-common-gradle clean assemble

    # copy artifacts to ARTIFACT_DIR
    cp -R build/libs/*.jar $ARTIFACT_DIR
  elif echo "$BUILD_SYSTEM" | grep -q 'maven'; then
    # maven
    # - version
    act-java-common-maven versions:set -DnewVersion=$NCI_COMMIT_REF_RELEASE

    # - build
    act-java-common-maven clean package

    # copy artifacts to ARTIFACT_DIR
    cp -R target/*.jar $ARTIFACT_DIR
  fi
}

# entrypoint
case "${1:-}" in
  help)
    echo "Build script for java projects"
    echo ""
    echo "Environment:"
    echo "* DEBUG: Can be set to true to enable debugging"
    echo "* ARTIFACT_DIR: The target directory for generated artifact files, defaults to /dist"
    ;;
  *)
    _log_message "Running action [$ACTION_CATEGORY.$ACTION_NAME]" "INFO"
    _prepare
    _run_hook "pre-$ACTION_CATEGORY-$ACTION_NAME"
    main "$@"
    _run_hook "post-$ACTION_CATEGORY-$ACTION_NAME"
;;
esac
