#!/usr/bin/env bash
set -euo pipefail
ACTION_CATEGORY="container"
ACTION_NAME="push"

# common
LOCAL_PATH=${BASH_SOURCE%/*}
source "$LOCAL_PATH/pipeline-common"
source "$LOCAL_PATH/action-common-container"

# main
function main()
{
  # login to registry
  container_registry_login "$NCI_CONTAINERREGISTRY_HOST" "$NCI_CONTAINERREGISTRY_USERNAME" "$NCI_CONTAINERREGISTRY_PASSWORD"

  # push image
  container_registry_push "${CONTAINER_REPO}:${CONTAINER_TAG}"
}

# entrypoint
case "${1:-}" in
  help)
    echo "Publish a container image on a registry."
    echo ""
    echo "Environment:"
    echo "* DEBUG: Can be set to true to enable debugging."
    echo "* DOCKERFILE_PATH: Path of the dockerfile, by default the current working directory."
    ;;
  *)
    _log_message "Running action [$ACTION_CATEGORY.$ACTION_NAME]" "INFO"
    _prepare
    _run_hook "pre-$ACTION_CATEGORY-$ACTION_NAME"
    main "$@"
    _run_hook "post-$ACTION_CATEGORY-$ACTION_NAME"
;;
esac
