#!/usr/bin/env bash
set -euo pipefail
ACTION_CATEGORY="python"
ACTION_NAME="run"

# common
LOCAL_PATH=${BASH_SOURCE%/*}
source "$LOCAL_PATH/pipeline-common"

# main
function main()
{
  # configuration
  ARTIFACT_DIR=${ARTIFACT_DIR:-dist}
  MAIN_FILE=${MAIN_FILE:-main.py}

  # make sure the directory exists
  mkdir -p $ARTIFACT_DIR

  # compile .py files
  _run_in_container python $MAIN_FILE
}

# entrypoint
case "${1:-}" in
  help)
    echo "Python Run"
    echo ""
    echo "Environment:"
    echo "* DEBUG: Can be set to true to enable debugging"
    echo "* ARTIFACT_DIR: The target directory for generated artifact files, defaults to /dist"
    ;;
  *)
    _log_message "Running action [$ACTION_CATEGORY.$ACTION_NAME]" "INFO"
    _prepare
    _run_hook "pre-$ACTION_CATEGORY-$ACTION_NAME"
    main "$@"
    _run_hook "post-$ACTION_CATEGORY-$ACTION_NAME"
;;
esac
