#!/usr/bin/env bash
set -euo pipefail
ACTION_CATEGORY="container"
ACTION_NAME="build"

# common
LOCAL_PATH=${BASH_SOURCE%/*}
source "$LOCAL_PATH/action-common"
source "$LOCAL_PATH/action-common-container"

# main
function main()
{
  # configuration
  DOCKERFILE_PATH=${DOCKERFILE_PATH:-.}
  DOCKERFILE_NAME=${DOCKERFILE_NAME:-Dockerfile}
  DOCKERFILE_URL_DEFAULT=${DOCKERFILE_URL_DEFAULT:-}
  CONTAINER_REPO=${CONTAINER_REPO:-$NCI_CONTAINERREGISTRY_REPOSITORY}
  CONTAINER_TAG=${CONTAINER_TAG:-$NCI_COMMIT_REF_RELEASE}
  ARTIFACT_BUILD_ARCHS=${ARTIFACT_BUILD_ARCHS:-linux_amd64}

  # support for DOCKERFILE_URL_DEFAULT
  if ! test -f "$DOCKERFILE_PATH/$DOCKERFILE_NAME"; then
    act-log-message "no local dockerfile provided at [$DOCKERFILE_PATH/$DOCKERFILE_NAME]!" "DEBUG"

    if [ -z "$DOCKERFILE_DEFAULT" ]; then
      act-log-message "no dockerfile provided at [$DOCKERFILE_PATH/$DOCKERFILE_NAME] and no DOCKERFILE_DEFAULT set!" "ERROR"
      exit 1
    else
      act-log-message "using default dockerfile from [$DOCKERFILE_DEFAULT] at [$DOCKERFILE_PATH/$DOCKERFILE_NAME]" "INFO"
      curl -L -s -o "$DOCKERFILE_PATH/$DOCKERFILE_NAME" "$DOCKERFILE_DEFAULT"
      USED_DEFAULT_DOCKER=true
    fi
  fi

  # build
  IFS=',' read -r -a artifactBuildArchArray <<< $(echo "$ARTIFACT_BUILD_ARCHS")
  for VALUE in "${artifactBuildArchArray[@]}"; do
    IFS='_' read -r -a row <<< "$VALUE"
    local buildOS="${row[0]}"
    local buildArch="${row[1]}"

    # run build
    build-container "$buildOS" "$buildArch"
  done

  # remove default dockerfile if used
  if echo "${USED_DEFAULT_DOCKER:-false}" | grep -q 'true'; then
    act-log-message "removed temporary dockerfile" "DEBUG"
    rm "$DOCKERFILE_PATH/$DOCKERFILE_NAME" >> /dev/null
  fi
}

# entrypoint
case "${1:-}" in
  help)
    echo "Used to package a app with a dockerfile"
    echo ""
    echo "Environment:"
    echo "* DEBUG: Can be set to true to enable debugging."
    echo "* DOCKERFILE_PATH: Path of the dockerfile, by default the current working directory."
    echo "* DOCKERFILE_NAME: Name of the dockerfile. (default: Dockerfile)"
    echo "* DOCKERFILE_URL_DEFAULT: A url to a default dockerfile to use, if the local dockerfile wasn't found/provided."
    ;;
  *)
    act-log-message "Running action [$ACTION_CATEGORY.$ACTION_NAME]" "INFO"
    act-common-prepare
    act-common-hook "pre-$ACTION_CATEGORY-$ACTION_NAME"
    main "$@"
    act-common-hook "post-$ACTION_CATEGORY-$ACTION_NAME"
;;
esac
