#!/usr/bin/env bash
set -euo pipefail
ACTION_CATEGORY="container"
ACTION_NAME="push"

# common
LOCAL_PATH=${BASH_SOURCE%/*}
source "$LOCAL_PATH/pipeline-common"
source "$LOCAL_PATH/action-common-container"

# main
function main()
{
  # configuration
  CONTAINER_REPO=${CONTAINER_REPO:-$NCI_CONTAINERREGISTRY_REPOSITORY}
  CONTAINER_TAG=${CONTAINER_TAG:-$NCI_COMMIT_REF_RELEASE}

  # login to registry
  act-common-container-registry-login

  # push image
  act-common-container-registry-push "${CONTAINER_REPO}:${CONTAINER_TAG}"
}

# entrypoint
case "${1:-}" in
  help)
    echo "Publish a container image on a registry."
    echo ""
    echo "Environment:"
    echo "* DEBUG: Can be set to true to enable debugging."
    echo "* DOCKERFILE_PATH: Path of the dockerfile, by default the current working directory."
    ;;
  *)
    _log_message "Running action [$ACTION_CATEGORY.$ACTION_NAME]" "INFO"
    _prepare
    _run_hook "pre-$ACTION_CATEGORY-$ACTION_NAME"
    main "$@"
    _run_hook "post-$ACTION_CATEGORY-$ACTION_NAME"
;;
esac
