#!/usr/bin/env bash
set -euo pipefail

# make sure the namespace / project exists - try to create it otherwise
function act-common-kubernetes-ensure-namespace {
  local TARGET_NAMESPACE=${1:-}
  if [ -z "$TARGET_NAMESPACE" ]; then
    _log_message "no target namespace specified as first argument when calling func act-common-kubernetes-ensure-namespace" "ERROR"
    exit 1
  fi

  _log_message "making sure namespace $TARGET_NAMESPACE exists ..." "DEBUG"
  set +e
  _run_in_container kubectl get namespace "$TARGET_NAMESPACE" >> /dev/null
  local getNamespaceStatus=$?
  set -e
  if [ "$getNamespaceStatus" -ne "0" ]; then
    ## create namespace
    _log_message "creating namespace $TARGET_NAMESPACE" "INFO"
    _run_in_container kubectl create namespace "$TARGET_NAMESPACE"
  else
    _log_message "namespace exists. skipping creation ..." "DEBUG"
  fi
}

# download_chart
function act-common-kubernetes-download-chart
{
  local CHART_ID=${1:-}

  # prepare helm cli
  _log_message "Initializing Helm ..." "DEBUG"
  _run_in_container helm init --client-only --skip-refresh &> /dev/null

  # print variable content
  local CHART_REPOSITORY=$(echo $CHART_ID | cut -d '/' -f 1)

  # Check if the repository is known / needs to be added for the deployment to work
  _log_message "Chart Repository: ${CHART_REPOSITORY}" "DEBUG"
  if [ "$CHART_REPOSITORY" != "stable" ]; then
    ## if the repo isn't stable/ then we're using a custom repository that we need to initialize
    _log_message "Using custom chart repository: ${CHART_REPOSITORY}" "DEBUG"

    if [ "$CHART_REPOSITORY" == "incubator" ]; then
      _run_in_container helm repo add incubator https://kubernetes-charts-incubator.storage.googleapis.com &> /dev/null
    elif [ "$CHART_REPOSITORY" == "rancher-stable" ]; then
      _run_in_container helm repo add rancher-stable https://releases.rancher.com/server-charts/stable &> /dev/null
    elif [ "$CHART_REPOSITORY" == "appscode" ]; then
      _run_in_container helm repo add appscode https://charts.appscode.com/stable &> /dev/null
    elif [ "$CHART_REPOSITORY" == "gitlab" ]; then
      _run_in_container helm repo add gitlab https://charts.gitlab.io &> /dev/null
    elif [ "$CHART_REPOSITORY" == "jetstack" ]; then
      _run_in_container helm repo add jetstack https://charts.jetstack.io &> /dev/null
    elif [ "$CHART_REPOSITORY" == "philippheuer" ]; then
      _run_in_container helm repo add philippheuer https://philippheuer.gitlab.io/kubernetes-charts &> /dev/null
    fi
  fi
  _run_in_container helm repo update &> /dev/null
}

# initialize tiller
function act-common-kubernetes-initialize-tiller
{
  # check if tiller was already initialized
  set +e
  _run_in_container kubectl get serviceaccount --namespace ${DEPLOYMENT_NAMESPACE} tiller >> /dev/null
  local getTillerServiceAccountStatus=$?
  set -e
  if [ "$getTillerServiceAccountStatus" -ne "0" ]; then
    _log_message "Service account missing, creating tiller service account ..." "DEBUG"

    ## Service Account
    _run_in_container kubectl create serviceaccount --namespace ${DEPLOYMENT_NAMESPACE} tiller

    ## Service Account Permissions (namespace admin or cluster admin, depending on $DEPLOYMENT_CLUSTER_ADMIN)
    if [ "$DEPLOYMENT_CLUSTER_ADMIN" == "true" ]; then
      _log_message "Granting tiller cluster admin role." "INFO"
      _run_in_container kubectl create clusterrolebinding ${DEPLOYMENT_NAMESPACE}-tiller-rule \
        --clusterrole=cluster-admin \
        --serviceaccount=${DEPLOYMENT_NAMESPACE}:tiller
    else
      _log_message "Granting tiller namespace admin role." "INFO"
      _run_in_container kubectl create rolebinding ${DEPLOYMENT_NAMESPACE}-tiller-binding \
        --namespace=${DEPLOYMENT_NAMESPACE} \
        --clusterrole=admin \
        --serviceaccount=${DEPLOYMENT_NAMESPACE}:tiller
    fi

    ## Install Tiller
    _run_in_container helm init \
      --tiller-namespace "${DEPLOYMENT_NAMESPACE}" \
      --service-account tiller \
      --history-max 3 \
      --upgrade \
      --wait >> /dev/null
    #--override 'spec.template.spec.containers[0].command'='{/tiller,--storage=secret}' \
  else
    _log_message "Tiller is initialized. skipping setup ..." "DEBUG"
  fi
}
