#!/usr/bin/env bash
set -euo pipefail

# function: detect build system
function act-java-common-detect
{
  if test -f "build.gradle"; then
    _log_message "Found a gradle project." "DEBUG"
    export BUILD_SYSTEM=gradle
  elif test -f "pom.xml"; then
    _log_message "Found a maven project." "DEBUG"
    export BUILD_SYSTEM=maven
  else
    _log_message "Could not detect java build system, please use either gradle or maven!" "ERROR"
    export BUILD_SYSTEM=unknown
    exit 1
  fi
}

# function: gradle
function act-java-common-gradle
{
  GRADLE_CALL=("-Dorg.gradle.appname=gradlew" "-classpath" "gradle/wrapper/gradle-wrapper.jar" "org.gradle.wrapper.GradleWrapperMain")

  # gradle wrapper
  if test -f "gradlew"; then
    # - make sure the gradle wrapper is present and executable.
    if test -f "gradle/wrapper/gradle-wrapper.jar"; then
      chmod +x gradle/wrapper/gradle-wrapper.jar
    fi

    # run build (This essentially downloads a copy of Gradle to build the project with.)
    _run_in_container java $JAVA_PROXY_OPTS ${GRADLE_CALL[@]} $@
  else
    _log_message "Gradle projects require the gradle wrapper to be commited into the repository! Check out https://docs.gradle.org/current/userguide/gradle_wrapper.html" "ERROR"
    exit 1
  fi
}

# function: maven
function act-java-common-maven
{
  # maven config
  M2_HOME=${M2_HOME:-/root/.m2}
  MAVEN_CONFIG=${MAVEN_CONFIG:-}
  MAVEN_DEFAULTVERSION=${MAVEN_DEFAULTVERSION:-3.6.2}

  # maven wrapper
  if test -f "mvnw"; then
    MAVEN_CALL=("-Dmaven.home=${M2_HOME}" "-Dmaven.multiModuleProjectDirectory=/project" "-classpath" ".mvn/wrapper/maven-wrapper.jar" "org.apache.maven.wrapper.MavenWrapperMain")

    # - make sure the maven wrapper is present
    if test -f ".mvn/wrapper/maven-wrapper.jar"; then
      echo "--> Maven wrapper .mvn/wrapper/maven-wrapper.jar is already present."
    else
      echo "--> Couldn't find .mvn/wrapper/maven-wrapper.jar, downloading it ..."
      mkdir -p .mvn/wrapper
      curl -L -s -o .mvn/wrapper/maven-wrapper.jar https://repo.maven.apache.org/maven2/io/takari/maven-wrapper/0.5.5/maven-wrapper-0.5.5.jar
    fi

    # - check for maven wrapper properties file
    if test -f ".mvn/wrapper/maven-wrapper.properties"; then
      _log_message "Maven wrapper configuration .mvn/wrapper/maven-wrapper.properties found." "DEBUG"
    else
      _log_message "Couldn't find .mvn/wrapper/maven-wrapper.properties, using maven $MAVEN_DEFAULTVERSION as default!" "WARN"
      echo "distributionUrl=https://repo1.maven.org/maven2/org/apache/maven/apache-maven/$MAVEN_DEFAULTVERSION/apache-maven-$MAVEN_DEFAULTVERSION-bin.zip" >> .mvn/wrapper/maven-wrapper.properties
    fi

    # run build
    _run_in_container java $JAVA_PROXY_OPTS ${MAVEN_CALL[@]} $MAVEN_CONFIG $@
  else
    _log_message "Maven projects require the maven wrapper to be commited into the repository! Check out https://www.baeldung.com/maven-wrapper" "ERROR"
    exit 1
  fi
}
