#!/usr/bin/env bash
set -euo pipefail
ACTION_CATEGORY="go"
ACTION_NAME="run"

# common
LOCAL_PATH=${BASH_SOURCE%/*}
source "$LOCAL_PATH/pipeline-common"

# main
function main()
{
    echo "-> execute: run"
    envcli run go run ./src "$@"
}

# entrypoint
case "${1:-}" in
  help)
    echo "Used to run a go application for local testing, passes all arguments after go-run to your go app"
    echo ""
    echo "Environment:"
    echo "* DEBUG: Can be set to true to enable debugging"
    ;;
  *)
    _log_message "Running action [$ACTION_CATEGORY.$ACTION_NAME]" "INFO"
    _prepare
    _run_hook "pre-$ACTION_CATEGORY-$ACTION_NAME"
    main "$@"
    _run_hook "post-$ACTION_CATEGORY-$ACTION_NAME"
;;
esac
