#!/usr/bin/env bash
set -euo pipefail
ACTION_CATEGORY="hugo"
ACTION_NAME="build"

# common
LOCAL_PATH=${BASH_SOURCE%/*}
source "$LOCAL_PATH/pipeline-common"

# main
function main()
{
  # configuration
  HUGO_SOURCE=${HUGO_SOURCE:-.}

  # get dependencies
  if test -f config.toml; then
    _run_in_container hugo --source "$HUGO_SOURCE" --destination "$ARTIFACT_DIR" --minify --gc --baseURL http://localhost
  else
    _log_message "Hugo needs a config.toml!" "ERROR"
    exit 1
  fi
}

# entrypoint
case "${1:-}" in
  help)
    echo "Hugo Build"
    echo ""
    echo "Environment:"
    echo "* DEBUG: Can be set to true to enable debugging"
    echo "* ARTIFACT_DIR: The target directory for generated artifact files, defaults to /dist"
    ;;
  *)
    _log_message "Running action [$ACTION_CATEGORY.$ACTION_NAME]" "INFO"
    _prepare
    _run_hook "pre-$ACTION_CATEGORY-$ACTION_NAME"
    main "$@"
    _run_hook "post-$ACTION_CATEGORY-$ACTION_NAME"
;;
esac
