#!/usr/bin/env bash
set -euo pipefail
ACTION_CATEGORY="Bintray"
ACTION_NAME="Publish"

# common
source "${BASH_SOURCE%/*}/common-pipeline-scripts"
onPreScript

# Used to publish the artifacts to bintray (/dist)
#
# Environment:
# * DEBUG: Can be set to true to enable debugging
# * ARTIFACT_DIR: All files from this directory will be published on bintray (default: dist)
# * BINTRAY_ORGANZATION: The organisation the package should be published in, can be identical to the username.
# * BINTRAY_REPOSITORY: The repository within the org/user.
# * BINTRAY_PACKAGE: The package that gets published in a repository within a org.
# * BINTRAY_USERNAME: Username used to authenticate with bintray.
# * BINTRAY_TOKEN: Access token for the provided username.

# configuration
ARTIFACT_DIR=${ARTIFACT_DIR:-dist}

# publish artifacts
for file in $ARTIFACT_DIR/*
do
  TARGET_PATH=$BINTRAY_PACKAGE/$NCI_COMMIT_REF_NAME/$(basename -- "$file")
  echo "--> Publishing $file to $TARGET_PATH ..."

  curl -T "$file" -u$BINTRAY_USERNAME:$BINTRAY_TOKEN https://api.bintray.com/content/$BINTRAY_ORGANZATION/$BINTRAY_REPOSITORY/$BINTRAY_PACKAGE/$NCI_COMMIT_REF_NAME/$TARGET_PATH
done
