#!/usr/bin/env bash
set -euo pipefail
ACTION_CATEGORY="CI"
ACTION_NAME="Debug"

# common
source common-pipeline-scripts
onPreScript

# usable env variables
echo "-> Execute: Print available environment variables"
printenv | grep NCI
