#!/usr/bin/env bash

function onPreScript {
  echo "Running Action $ACTION_CATEGORY.$ACTION_NAME"

  # debug mode
  DEBUG=${DEBUG:-false}
  if [ "$DEBUG" == "true" ]; then
      echo "-> Debugging mode enabled ..."
      set -x
  fi

  # normalize ci variables
  echo "-> Execute: NormalizeCI"
  eval $(normalizeci)

  # proxy
  export PROXY_HOST=${PROXY_HOST:-}
  export PROXY_PORT=${PROXY_PORT:-}
  export JAVA_PROXY_OPTS="-Dhttp.proxyHost=$PROXY_HOST -Dhttp.proxyPort=$PROXY_PORT -Dhttps.proxyHost=$PROXY_HOST -Dhttps.proxyPort=$PROXY_PORT"
}
