#!/usr/bin/env bash
set -euo pipefail
ACTION_CATEGORY="Go"
ACTION_NAME="Test"

# common
source "${BASH_SOURCE%/*}/common-pipeline-scripts"

# Used to run go tests
#
# Environment:
# * DEBUG: Can be set to true to enable debugging
# * VERBOSE: Will print additional test information on execution
VERBOSE=${VERBOSE:-false}

# run tests
echo "-> Execute: Tests"
if echo "$VERBOSE" | grep -q 'true'; then
    go test -v ./...
else
    go test ./...
fi
