#!/usr/bin/env bash
set -euo pipefail
ACTION_CATEGORY="Go"
ACTION_NAME="Test"

# common
source common-pipeline-scripts
onPreScript

# run tests
echo "-> Execute: Tests"
go test ./...
# go test -v ./... DEBUG
