#!/usr/bin/env bash
set -euo pipefail
ACTION_CATEGORY="Java"
ACTION_NAME="Build"

# common
source "${BASH_SOURCE%/*}/common-pipeline-scripts"

# configuration
echo "-> execute: configuration"
ARTIFACT_DIR=${ARTIFACT_DIR:-dist}

# make sure the directory exists
mkdir -p $ARTIFACT_DIR

# run
echo "-> execute: build"

if test -f "build.gradle"; then
  # gradle
  echo "--> build system: gradle"
  GRADLE_CALL=("-Dorg.gradle.appname=gradlew" "-classpath" "gradle/wrapper/gradle-wrapper.jar" "org.gradle.wrapper.GradleWrapperMain")

  # gradle wrapper
  if test -f "gradlew"; then
    # - make sure the gradle wrapper is present and executable.
    if test -f "gradle/wrapper/gradle-wrapper.jar"; then
      chmod +x gradle/wrapper/gradle-wrapper.jar
    fi

    # run build (This essentially downloads a copy of Gradle to build the project with.)
    java $JAVA_PROXY_OPTS ${GRADLE_CALL[@]} assemble

    # copy artifacts to ARTIFACT_DIR
    cp -R build/libs/*.jar $ARTIFACT_DIR
  else
    echo "Gradle projects require the gradle wrapper to be commited into the repository! Check out https://docs.gradle.org/current/userguide/gradle_wrapper.html"
    exit 1
  fi
elif test -f "pom.xml"; then
  # maven config
  M2_HOME=${M2_HOME:-/root/.m2}
  MAVEN_CONFIG=${MAVEN_CONFIG:-}
  MAVEN_DEFAULTVERSION=${MAVEN_DEFAULTVERSION:-3.6.2}
  
  # maven wrapper
  if test -f "mvnw"; then
    MAVEN_CALL=("-Dmaven.home=${M2_HOME}" "-Dmaven.multiModuleProjectDirectory=/project" "-classpath" ".mvn/wrapper/maven-wrapper.jar" "org.apache.maven.wrapper.MavenWrapperMain")
    
    # - make sure the maven wrapper is present
    if test -f ".mvn/wrapper/maven-wrapper.jar"; then
      echo "--> Maven wrapper .mvn/wrapper/maven-wrapper.jar is already present." 
    else
      echo "--> Couldn't find .mvn/wrapper/maven-wrapper.jar, downloading it ..."
      mkdir -p .mvn/wrapper
      curl -L -s -o .mvn/wrapper/maven-wrapper.jar https://repo.maven.apache.org/maven2/io/takari/maven-wrapper/0.5.5/maven-wrapper-0.5.5.jar
    fi

    # - check for maven wrapper properties file
    if test -f ".mvn/wrapper/maven-wrapper.properties"; then
      echo "--> Maven wrapper configuration .mvn/wrapper/maven-wrapper.properties found." 
    else
      echo "--> Warning: Couldn't find .mvn/wrapper/maven-wrapper.properties, using maven $MAVEN_DEFAULTVERSION as default!"
      echo "distributionUrl=https://repo1.maven.org/maven2/org/apache/maven/apache-maven/$MAVEN_DEFAULTVERSION/apache-maven-$MAVEN_DEFAULTVERSION-bin.zip" >> .mvn/wrapper/maven-wrapper.properties
    fi

    # run build
    echo "java $JAVA_PROXY_OPTS ${MAVEN_CALL[@]} clean package"
    java $JAVA_PROXY_OPTS ${MAVEN_CALL[@]} $MAVEN_CONFIG clean package

    # copy artifacts to ARTIFACT_DIR
    cp -R target/*.jar $ARTIFACT_DIR
  else
    echo "Maven projects require the maven wrapper to be commited into the repository! Check out https://www.baeldung.com/maven-wrapper"
    exit 1
  fi
else
  echo "--> error: unknown build system!"
  echo "Supported are: gradle, maven"
  exit 1
fi
