#!/usr/bin/env bash
set -euo pipefail
ACTION_CATEGORY="Optimize"
ACTION_NAME="UPX"

# Used to compress executable files using upx (the Ultimate Packer for eXecutables)
#
# Environment:
# * DEBUG: Can be set to true to enable debugging
# * ARTIFACT_DIR: All files from this directory will be published on bintray (default: dist)
# * UPX_ARGS: Default is `--brute`, use `--best --ultra-brute` for best compression.

# common
source common-pipeline-scripts
onPreScript

# configuration
ARTIFACT_DIR=${ARTIFACT_DIR:-dist}
UPX_ARGS=${UPX_ARGS:---brute}

# execute
echo "-> Execute: Optimization"
for file in $ARTIFACT_DIR/*
do
  echo "--> Compressing $file ..."
  upx $UPX_ARGS "$file"
done
