#!/usr/bin/env bash
set -euo pipefail
STAGE_NAME="package"

# common
LOCAL_PATH=${BASH_SOURCE%/*}
source "$LOCAL_PATH/action-common"

# main
function main()
{
  # don't package library projects for any language
  if [[ ${PROJECT_TYPE} =~ ^.*-library$ ]]; then
    echo "-> not packaging library projects!"
    exit 0
  fi

  # by project type
  if [[ ${PROJECT_TYPE} =~ ^java-.*$ ]]; then
    # java
    export DOCKERFILE_URL_DEFAULT="$MPI_RESOURCES_MIRROR/java-service.dockerfile"
    action-package-dockerfile
  else
    echo "warning: project type ${PROJECT_TYPE} is not supported!"
  fi

  # by deployment type
  if [[ ${DEPLOYMENT_TYPE} == "bintray" ]]; then
    # for cli and libraries, TODO: add filter later
    echo "-> will publish a bintray package with the artifacts ..."
    action-bintray-publish
  fi
}

# entrypoint
case "${1:-}" in
  help)
    echo "Stage - Test"
    echo "Will execute test cases"
    echo ""
    echo "Environment:"
    echo "* DEBUG: Can be set to true to enable debugging"
    ;;
  *)
    echo "Running stage [$STAGE_NAME]"
    act-common-prepare
    act-common-hook "pre-$STAGE_NAME"
    main "$@"
    act-common-hook "post-$STAGE_NAME"
;;
esac
