#!/usr/bin/env bash
set -euo pipefail
STAGE_NAME="prepare"

# common
LOCAL_PATH=${BASH_SOURCE%/*}
source "$LOCAL_PATH/pipeline-common"

# main
function main()
{
  # container
  if [[ ${PROJECT_TYPE} =~ ^container-.*$ ]]; then
    _log_message "does not need any preparation." "INFO"
    exit 0
  fi

  # container
  if [[ ${PROJECT_TYPE} =~ ^golang-.*$ ]]; then
    _log_message "pulling images ..." "INFO"
    envcli pull-image go upx
    exit 0
  fi

  # deployment
  if [[ ${PROJECT_TYPE} =~ ^deployment*$ ]]; then
    # check for invalid combinations
    if [[ ${DEPLOYMENT_TYPE} =~ ^none*$ ]]; then
      _log_message "project type [${PROJECT_TYPE}] is not supported with deployment type [${DEPLOYMENT_TYPE}]!" "ERROR"
      exit 1
    fi
    exit 0
  fi

  # java
  if [[ ${PROJECT_TYPE} =~ ^java-.*$ ]]; then
    _log_message "pulling images ..." "INFO"
    envcli pull-image java
    exit 0
  fi

  # no match
  _log_message "project type ${PROJECT_TYPE} does not support prepare yet!" "WARN"
}

# entrypoint
case "${1:-}" in
  help)
    echo "Stage - Prepare"
    echo "Will make sure that all requirements by the pipeline script are fulfilled."
    echo ""
    echo "Environment:"
    echo "* DEBUG: Can be set to true to enable debugging"
    ;;
  *)
    _log_message "Running action [$STAGE_NAME]" "INFO"
    _prepare
    _run_hook "pre-$STAGE_NAME"
    main "$@"
    _run_hook "post-$STAGE_NAME"
;;
esac
