#!/usr/bin/env bash
set -euo pipefail
STAGE_NAME="prepare"

# common
LOCAL_PATH=${BASH_SOURCE%/*}
source "$LOCAL_PATH/action-common"

# main
function main()
{
  # by project type
  if [[ ${PROJECT_TYPE} =~ ^golang-.*$ ]]; then
    # golang
    echo "-> pulling required container images ..."
    envcli pull-image go upx
  elif [[ ${PROJECT_TYPE} =~ ^java-.*$ ]]; then
    # java
    echo "-> pulling required container images ..."
    envcli pull-image java
  elif [[ ${PROJECT_TYPE} =~ ^dockerfile-.*$ ]]; then
    # dockerfile artifact-delivery based projects
    echo "-> doing nothing."
  else
    echo "error: project type ${PROJECT_TYPE} is not supported!"
    exit 1
  fi

  # by deployment type
}

# entrypoint
case "${1:-}" in
  help)
    echo "Stage - Prepare"
    echo "Will make sure that all requirements by the pipeline script are fulfilled."
    echo ""
    echo "Environment:"
    echo "* DEBUG: Can be set to true to enable debugging"
    ;;
  *)
    echo "Running stage [$STAGE_NAME]"
    act-common-prepare
    act-common-hook "pre-$STAGE_NAME"
    main "$@"
    act-common-hook "post-$STAGE_NAME"
;;
esac
