#!/usr/bin/env bash
set -euo pipefail
STAGE_NAME="performance"

# common
LOCAL_PATH=${BASH_SOURCE%/*}
source "$LOCAL_PATH/action-common"

# main
function main()
{
  act-log-message "no checks supported yet ..." "INFO"
}

# entrypoint
case "${1:-}" in
  help)
    echo "Stage - Performance"
    echo "Run Performance tasks to check application performance."
    echo ""
    echo "Environment:"
    echo "* DEBUG: Can be set to true to enable debugging"
    ;;
  *)
    act-log-message "Running stage [$STAGE_NAME]" "INFO"
    act-common-prepare
    act-common-hook "pre-$STAGE_NAME"
    main "$@"
    act-common-hook "post-$STAGE_NAME"
;;
esac
