#!/usr/bin/env bash
set -euo pipefail
STAGE_NAME="publish"

# common
LOCAL_PATH=${BASH_SOURCE%/*}
source "$LOCAL_PATH/action-common"

# main
function main()
{
  # container
  if test -f "dist/container-image/main.tar"; then
    # import image
    act-log-message "publishing container image from dist/container-image/main.tar" "INFO"
    docker load -i dist/container-image/main.tar

    # publish
    action-container-push
  fi

  # bintray
  if [[ ${DEPLOYMENT_TYPE} == "bintray" ]]; then
    # for cli and libraries, TODO: add filter later
    act-log-message "publishing bintray artifacts from dist/" "INFO"
    action-bintray-publish
  fi
}

# entrypoint
case "${1:-}" in
  help)
    echo "Stage - Publish"
    echo "Will publish artifacts"
    echo ""
    echo "Environment:"
    echo "* DEBUG: Can be set to true to enable debugging"
    ;;
  *)
    act-log-message "Running stage [$STAGE_NAME]" "INFO"
    act-common-prepare
    act-common-hook "pre-$STAGE_NAME"
    main "$@"
    act-common-hook "post-$STAGE_NAME"
;;
esac
