#!/usr/bin/env bash
set -euo pipefail
STAGE_NAME="prepare"

# common
LOCAL_PATH=${BASH_SOURCE%/*}
source "$LOCAL_PATH/action-common"

# main
function main()
{
  # container
  if [[ ${PROJECT_TYPE} =~ ^container-.*$ ]]; then
    act-log-message "does not need any preparation." "INFO"
    exit 0
  fi

  # container
  if [[ ${PROJECT_TYPE} =~ ^golang-.*$ ]]; then
    act-log-message "pulling images ..." "INFO"
    envcli pull-image go upx
    exit 0
  fi

  # java
  if [[ ${PROJECT_TYPE} =~ ^java-.*$ ]]; then
    act-log-message "pulling images ..." "INFO"
    envcli pull-image java
    exit 0
  fi

  # no match
  act-log-message "project type ${PROJECT_TYPE} does not support prepare yet!" "WARN"
}

# entrypoint
case "${1:-}" in
  help)
    echo "Stage - Prepare"
    echo "Will make sure that all requirements by the pipeline script are fulfilled."
    echo ""
    echo "Environment:"
    echo "* DEBUG: Can be set to true to enable debugging"
    ;;
  *)
    act-log-message "Running stage [$STAGE_NAME]" "INFO"
    act-common-prepare
    act-common-hook "pre-$STAGE_NAME"
    main "$@"
    act-common-hook "post-$STAGE_NAME"
;;
esac
