#!/usr/bin/env bash
set -euo pipefail
STAGE_NAME="build"

# common
LOCAL_PATH=${BASH_SOURCE%/*}
source "$LOCAL_PATH/action-common"

# main
function main()
{
  # container
  if [[ ${PROJECT_TYPE} =~ ^container-.*$ ]]; then
    action-container-build
    exit 0
  fi

  # golang
  if [[ ${PROJECT_TYPE} =~ ^golang-.*$ ]]; then
    action-go-build
    exit 0
  fi

  # java
  if [[ ${PROJECT_TYPE} =~ ^java-.*$ ]]; then
    action-java-build
    exit 0
  fi

  # no match
  act-log-message "project type ${PROJECT_TYPE} is not supported!" "WARN"
}

# entrypoint
case "${1:-}" in
  help)
    echo "Stage - Build"
    echo "Will build the artifacts."
    echo ""
    echo "Environment:"
    echo "* DEBUG: Can be set to true to enable debugging"
    ;;
  *)
    act-log-message "Running stage [$STAGE_NAME]" "INFO"
    act-common-prepare
    act-common-hook "pre-$STAGE_NAME"
    main "$@"
    act-common-hook "post-$STAGE_NAME"
;;
esac
