#!/usr/bin/env bash
set -euo pipefail
STAGE_NAME="performance"

# common
LOCAL_PATH=${BASH_SOURCE%/*}
source "$LOCAL_PATH/pipeline-common"

# main
function main()
{
  _log_message "no checks supported yet ..." "INFO"
}

# entrypoint
case "${1:-}" in
  help)
    echo "Stage - Performance"
    echo "Run Performance tasks to check application performance."
    echo ""
    echo "Environment:"
    echo "* DEBUG: Can be set to true to enable debugging"
    ;;
  *)
    _log_message "Running action [$STAGE_NAME]" "INFO"
    _prepare
    _run_hook "pre-$STAGE_NAME"
    main "$@"
    _run_hook "post-$STAGE_NAME"
;;
esac
