#!/usr/bin/env bash
set -euo pipefail
STAGE_NAME="test"

# common
LOCAL_PATH=${BASH_SOURCE%/*}
source "$LOCAL_PATH/action-common"

# main
function main()
{
  # bash
  if [[ ${PROJECT_TYPE} =~ ^bash-.*$ ]]; then
    action-shell-test
    exit 0
  fi

  # container
  if [[ ${PROJECT_TYPE} =~ ^container-.*$ ]]; then
    act-log-message "no tests for containers yet ..." "WARN"
    exit 0
  fi

  # golang
  if [[ ${PROJECT_TYPE} =~ ^golang-.*$ ]]; then
    action-go-test
    exit 0
  fi

  # java
  if [[ ${PROJECT_TYPE} =~ ^java-.*$ ]]; then
    action-java-test
    exit 0
  fi

  # no match
  act-log-message "project type ${PROJECT_TYPE} does not support tests yet!" "WARN"
}

# entrypoint
case "${1:-}" in
  help)
    echo "Stage - Test"
    echo "Will execute test cases"
    echo ""
    echo "Environment:"
    echo "* DEBUG: Can be set to true to enable debugging"
    ;;
  *)
    act-log-message "Running stage [$STAGE_NAME]" "INFO"
    act-common-prepare
    act-common-hook "pre-$STAGE_NAME"
    main "$@"
    act-common-hook "post-$STAGE_NAME"
;;
esac
