#!/usr/bin/env bash
set -euo pipefail
STAGE_NAME="build"

# common
LOCAL_PATH=${BASH_SOURCE%/*}
source "$LOCAL_PATH/pipeline-common"

# main
function main()
{
  # container
  if [[ ${PROJECT_TYPE} =~ ^container-.*$ ]]; then
    action-container-build
    exit 0
  fi

  # golang
  if [[ ${PROJECT_TYPE} =~ ^golang-.*$ ]]; then
    action-go-build
    exit 0
  fi

  # hugo
  if [[ ${PROJECT_TYPE} =~ ^hugo-http$ ]]; then
    action-hugo-build
    exit 0
  fi

  # java
  if [[ ${PROJECT_TYPE} =~ ^java-.*$ ]]; then
    action-java-build
    exit 0
  fi

  # python
  if [[ ${PROJECT_TYPE} =~ ^python-.*$ ]]; then
    action-python-build
    exit 0
  fi

  # no match
  act-log-message "project type ${PROJECT_TYPE} is not supported!" "WARN"
}

# entrypoint
case "${1:-}" in
  help)
    echo "Stage - Build"
    echo "Will build the artifacts."
    echo ""
    echo "Environment:"
    echo "* DEBUG: Can be set to true to enable debugging"
    ;;
  *)
    _log_message "Running action [$STAGE_NAME]" "INFO"
    _prepare
    _run_hook "pre-$STAGE_NAME"
    main "$@"
    _run_hook "post-$STAGE_NAME"
;;
esac
