#!/usr/bin/env bash
set -euo pipefail
STAGE_NAME="test"

# common
LOCAL_PATH=${BASH_SOURCE%/*}
source "$LOCAL_PATH/action-common"

# main
function main()
{
  # by project type
  if [[ ${PROJECT_TYPE} =~ ^golang-.*$ ]]; then
    # golang
    action-go-test
  elif [[ ${PROJECT_TYPE} =~ ^java-.*$ ]]; then
    # java
    action-java-test
  elif [[ ${PROJECT_TYPE} =~ ^container-.*$ ]]; then
    # container
    echo "-> no tests for containers yet ..."
  else
    echo "error: project type ${PROJECT_TYPE} is not supported!"
    exit 1
  fi

  # by deployment type
}

# entrypoint
case "${1:-}" in
  help)
    echo "Stage - Test"
    echo "Will execute test cases"
    echo ""
    echo "Environment:"
    echo "* DEBUG: Can be set to true to enable debugging"
    ;;
  *)
    echo "Running stage [$STAGE_NAME]"
    act-common-prepare
    act-common-hook "pre-$STAGE_NAME"
    main "$@"
    act-common-hook "post-$STAGE_NAME"
;;
esac
